---
# This is a sample database file for the ActiveRecord ORM
:development: &defaults
  :adapter: mysql
  :database: merblisher_development
  :user: root
  :password:

:test:
  <<: *defaults
  :database: db/test.db

:production:
  <<: *defaults
  :database: db/production.db